name: bheopt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - folium
  - matplotlib
  - plotly
  - PIL
  - streamlit
  - joblib
  - pyproj
  - pip
  # If you need any pip-only packages, add them here:
  # - pip:
  #     - package_name
