name: bheopt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - folium
  - matplotlib
  - plotly
  - PIL
  - streamlit
  - streamlit_folium
  - joblib
  - pyproj
  - random
  - math
  - pip

